### PR TITLE
Fix deprecation warnings due to 'cl package dependency.

### PR DESCRIPTION
**Pull request by hdasch**
Migrate cl dependencies to cl-lib to quash deprecation warnings.

This includes pull request #38, as I do not see a good way of just submitting the deprecation fixes.  The pull requests are not related.

Guidance or correction gratefully accepted.

### CODE REVIEW

**Comment by hdasch** [comment]
Thank you for the feedback.  I have backed out the changes unrelated to the deprecation of cl.el.  I will submit another pull request to pick up those other changes.

**Comment by scymtym** [comment]
Thank you for the changes. Can you squash everything into single commit and update this pull request?

**Comment by hdasch** [comment]
Certainly.  Squash and push complete.

**Comment by scymtym** [comment]
> Certainly. Squash and push complete.

Thank you. Is it possible that the commit ended up with the wrong commit message?

**Comment by scymtym** [comment]
> Sigh. I really need to slow down and review my changes more closely.

No worries

> I have fixed the commit message. Thanks.

Looks good, thank you.

**Pull request merged**
