### PR TITLE
Backport pull requests, use cl-syslog

### LINKED ISSUE #1: JOIN-THREAD-ERROR
See https://github.com/7max/log4cl/issues/35 .

### PR DESCRIPTION
**Pull request by dkochmanski**
Closes #1.

### CODE REVIEW

**Comment by dkochmanski** [comment]
@knobo @scymtym @fukamachi 
Hey, I've backported your PRs to this repository.

@scymtym I have made syslog-appender use cl-syslog, like you have suggested in NEWS.

**Comment by dkochmanski** [comment]
disabled syslog-appender for abcl, because I can't load cffi on my `1.4.0` version (despite having jna on the host).

**Comment by scymtym** [comment]
> Hey, I've backported your PRs to this repository.

Thank you for your work.

> @scymtym I have made syslog-appender use cl-syslog, like you have suggested in NEWS.

Is depending on ``cl-syslog`` on SBCL intentional? If so, does that make ``log4cl`` depend on ``cffi`` and an ffi-based syslog interface on all lisps (except ABCL)?

If that is the case, I suggest having two versions of ``syslog-appender.lisp``: one for SBCL and other lisps with builtin syslog support and one for other lisps. That way, the ``cffi`` dependency is avoided unless unavoidable.

**Comment by scymtym** [comment]
> If that is the case, I suggest having two versions of syslog-appender.lisp: one for SBCL and other lisps with builtin syslog support and one for other lisps. That way, the cffi dependency is avoided unless unavoidable.

Alternatively, ``cl-syslog`` could use builtin syslog support on implementations that have it.

**Comment by scymtym** [comment]
I think 0c2288ea should use a condition variable to avoid the dependency on ``bt-semaphore``.

**Comment by dkochmanski** [comment]
> Is depending on cl-syslog on SBCL intentional? If so, does that make log4cl depend on cffi and an ffi-based syslog interface on all lisps (except ABCL)?

> If that is the case, I suggest having two versions of syslog-appender.lisp: one for SBCL and other lisps with builtin syslog support and one for other lisps. That way, the cffi dependency is avoided unless unavoidable.

Yes, that was intentional to simplify implementation. Do you think it's a bad idea to make `cffi` a dependency? I think that if that's a case, then we may create a separate system, which adds a syslog support (and in this system, say `log4cl/syslog`, we may have implementation-specific files and a generic one for others). What do you think?

> I think 0c2288e should use a condition variable to avoid the dependency on bt-semaphore.
Is there a reason we should avoid dependency on `bt-semaphore`? Also, as far as I understand, bt-sempahore is needed to fix a bug with joining threads.

**Comment by scymtym** [comment]
> Yes, that was intentional to simplify implementation. Do you think it's a bad idea to make cffi a dependency? I think that if that's a case, then we may create a separate system, which adds a syslog support (and in this system, say log4cl/syslog, we may have implementation-specific files and a generic one for others). What do you think?

I'm in favor of having a separate system for syslog support. My preferred solution would be such a system combined with a change in ``cl-syslog`` that uses builtin syslog support on implementations that have it.

This would preserve the ability to use ``log4cl`` without pulling in ``cffi`` on all implementations. And using the syslog appender would only pull in ``cffi`` when necessary.

**Comment by scymtym** [comment]
> Is there a reason we should avoid dependency on bt-semaphore? 

The fewer dependencies, the better. Especially for fundamental functionality like logging.

> Also, as far as I understand, bt-sempahore is needed to fix a bug with joining threads.

I think a condition variable (supported by ``bordeaux-threads``) is sufficient and not more complicated to use. That said, I'm not entirely sure how the support for timeout compares between ``bordeaux-threads`` and ``bt-semaphore`` in terms of portability and backward compatibility.

**Comment by dkochmanski** [comment]
condition-variables are supported in ECL, but timeout is not atm (https://gitlab.com/embeddable-common-lisp/ecl/blob/develop/src/c/threads/condition_variable.d#L80).

**Comment by scymtym** [comment]
> That said, I'm not entirely sure how the support for timeout compares between bordeaux-threads and bt-semaphore in terms of portability and backward compatibility.

> condition-variables are supported in ECL, but timeout is not atm (https://gitlab.com/embeddable-common-lisp/ecl/blob/develop/src/c/threads/condition_variable.d#L80).

``bt-semaphore`` implements its timeout via ``with-timeout`` (even for lisps that support proper timeouts) which translates to ``interrupt-thread`` and ``throw`` which is not generally safe.

So using ``(bt:condition-wait … :timeout …)`` on implementations that support and don't support proper timeouts and ``(bt:with-timeout (bt:condition-wait …))`` on other implementations would
* be better for implementations with proper timeouts
* be no worse for implementations without them
* get rid of the dependency

**Comment by dkochmanski** [comment]
Regarding sbcl-specific syslog:
- your implementation carries same syslog handler through subsequent log calls
- cl-syslog opens, logs and closes the handler for each log call

Do we want to have it consistent, or you'd rather prefer to make `sbcl` behave slightly different?

**Comment by scymtym** [comment]
> Do we want to have it consistent, or you'd rather prefer to make sbcl behave slightly different?

IMO, using one variant consistently would be better. I couldn't find anything definitive regarding which style is preferable, though. http://perldoc.perl.org/Sys/Syslog.html mildly suggests using a single ``openlog`` call for multiple ``syslog`` calls.

**Comment by dkochmanski** [comment]
syslog part fixed (I've extracted common part into separate file).

**Comment by knobo** [comment]
About join-thread problems. Should bt-semaphore be fixed or log4cl? Probably a good idea to fix log4cl to avoide the dependency. I just used bt-semaphore so I did not have to test every lisp-implementation myself. Since it looked like log4cl did not have any more development I did not bother to put resources in to that.

**Comment by knobo** [comment]
My abcl fix should also be analyzed. Maybe use #+abcl for that fix.

**Comment by dkochmanski** [comment]
I have run tests on some lisps and abcl fix doesn't seem to break anything. What is a right thing here – recursive lock or normal lock? If the latter,, why abcl needs a recursive one?

Regarding bt-sempahore: I don't have strong opinion on that. Library is very minimal and is a clear addendum to bordeaux-threads, so I would say let's fix it in `bt-semaphore`.

**Pull request merged**
